name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node.js
      uses: actions/setup-node@v2
    - name: Build
      run: npm run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "OpenRCT2 Title Sequence Editor"
        path: out/title-editor.js
